import '../styles/globals.css'
import Head from 'next/head'
import "semantic-ui-css/semantic.min.css";
import { DappProvider } from "../contexts/DappContexts";
function MyApp ( { Component, pageProps } )
{
  
  return (
    // <DappProvider>
    
       <Head>
        <title>XendTransfer_v2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component { ...pageProps } />
    // </DappProvider>
     

    
  )

}

export default MyApp
